"""Generate a standalone Python seed generation script from a ConceptualModel."""

from __future__ import annotations

from ..model import ConceptualModel


def generate_seed_script(model: ConceptualModel, rows_per_entity: int = 50) -> str:
    """Return a standalone Python script that generates seed CSVs for the model."""
    entity_lines = []
    for entity in model.entities:
        entity_lines.append(f"    # {entity.name}: {entity.description or 'no description'}")

    return f'''#!/usr/bin/env python3
"""
Auto-generated seed data generator for: {model.name}
Generated by infomodel-dbt-generator v0.1.0

Usage:
    python generate_seeds.py [--output ./seeds] [--rows 50] [--seed 42]

Outputs one CSV per entity into the specified output directory.
"""

import argparse
import os
import sys

# Add parent directory to path if running standalone
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from infomodeling import parser
from infomodeling.seeds.generator import generate_seeds, seeds_to_csv


MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "examples", "org_model.yaml")


def main():
    p = argparse.ArgumentParser(description="Generate seed CSV files from the conceptual model")
    p.add_argument("--model", default=MODEL_PATH, help="Path to conceptual model YAML")
    p.add_argument("--output", default="seeds", help="Output directory for CSV files")
    p.add_argument("--rows", type=int, default={rows_per_entity}, help="Rows per entity")
    p.add_argument("--seed", type=int, default=None, help="Random seed for deterministic output")
    args = p.parse_args()

    print(f"Loading model from: {{args.model}}")
    model = parser.load(args.model)
    print(f"Model loaded: {{model.name}} ({{len(model.entities)}} entities)")

    print(f"Generating {{args.rows}} rows per entity...")
    seeds = generate_seeds(model, rows_per_entity=args.rows, seed=args.seed)

    os.makedirs(args.output, exist_ok=True)
    for snake_name, rows in seeds.items():
        path = os.path.join(args.output, f"{{snake_name}}.csv")
        with open(path, "w") as f:
            f.write(seeds_to_csv(rows))
        print(f"  Wrote {{len(rows)}} rows → {{path}}")

    print(f"Done. {{len(seeds)}} CSV files written to {{args.output}}/")


if __name__ == "__main__":
    main()
'''
